[features]

[database.mysql]
username = "example-user"
password_env = "example_user_mysql_password"
hostname = "127.0.0.1"
port = 3306
database = "coastguard"

[smtp]
host="smtp.sendgrid.net"
port=587
username="apikey"
from_alias="Coastguard"
from_header="noreply@example.com"
reply_to_address="noreply@example.com"
password_env="smtp_password"