stages:
  - build_cli_rust_binary

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  GIT_STRATEGY: clone

build_rust_binary:
  image: rust:latest
  stage: build_cli_rust_binary
  script:
    - rustc --version && cargo --version
    - apt update -y && apt install zip tree -y
    - tree /
    - cd /builds/lighthouse-search/coastguard/cli
    - cargo build --verbose --release
    - cargo test --verbose
    - mkdir /builds/lighthouse-search/release
    - mv /builds/lighthouse-search/coastguard/cli/target/release/rust-cli /builds/lighthouse-search/release
    - tree /builds
    - zip -r /builds/lighthouse-search/coastguard/coastguard-cli.zip /builds/lighthouse-search/release
  artifacts:
    paths:
      - /builds/lighthouse-search/coastguard/coastguard-cli.zip